### PR TITLE
Migrations in test app

### PR DESCRIPTION
**Pull request by jkburges**

### CODE REVIEW

**Comment by jkburges** [comment]
I anticipate that there may need to be a small amount of config added to the jenkins build for this change to pass.  Specifically, blowing away and reconfiguring the test DB for each build.  e.g.

```
dropdb aatams_test
createdb -O aatams_test aatams_test
psql -c "create extension postgis schema public;" aatams_test
psql -c "create schema aatams authorization aatams_test;" aatams_test
psql -c "alter database aatams_test set search_path to 'aatams', 'public';" aatams_test
```

**Comment by dnahodil** [comment]
Where is the new MigrationUtils class used?

**Comment by jkburges** [comment]
> Where is the new MigrationUtils class used?

There is a fix to the migration plugin which allows migrations to be run during `test-app`, see: https://github.com/grails-plugins/grails-database-migration/pull/10

Unfortunately, the PR above is only in more recent versions of the plugin, which are *not* available/compatible with grails 1.3.7

This class then is a back-port of this fix - it overrides the same class included with the plugin.

**Comment by dnahodil** [comment]
Ok, cool. I was wondering if we had upgraded the plugin at all, but that explains it.

**Pull request merged**
