### PR TITLE
Remove unused pages from web-app

### PR DESCRIPTION
**Pull request by dnahodil**
This removes pages which shouldn't be used for Species and Animal. We shouldn't be directly modifying Animals in the app (only via AnimalReleases). We also shouldn't be accessing Species directly. The Species pages actually had errors that stopped them from working which is proof that they aren't used.

It is possible that these left-over pages contributed to some incorrect data in the system, but there's no proof of that.

See #122 and #123

### CODE REVIEW

**Comment by dnahodil** [comment]
I went through the controllers in the web-app and these seemed to be the only ones which had pages which shouldn't be used. Some other domain classes which shouldn't have had pages had already had the pages removed.

**Comment by xhoenner** [comment]
@julian1, @pblain this PR, along with https://github.com/aodn/aatams/pull/281, still need to be reviewed.

**Comment by julian1** [comment]
@xhoenner 

https://144.6.232.63/aatams/ has this fix.

Can you show me, how to replicate?

**Comment by xhoenner** [comment]
Looking good to me, I've tested all the combinations and it seems like this PR fixes up all the issues @dnahodil had identified.

The only thing I noticed was that it is possible to create a new person without being logged in (https://aatams.emii.org.au/aatams/person/create). I don't think this should be allowed, @jkburges ?

**Comment by jkburges** [comment]
> I don't think [creating a new person when unauthorised] should be allowed?

This *might* be required when unauthenticated users register - you'd need to check what that does.

**Comment by xhoenner** [comment]
You're right @jkburges, clicking on the 'Register' button in the right hand corner redirects you to https://aatams.emii.org.au/aatams/person/create. So all good @julian1, happy for you to merge this PR.

**Pull request merged**
