### PR TITLE
Add new code to generate monthly reports in the test folder

### PR DESCRIPTION
**Pull request by xhoenner**
@jkburges hopefully I've put these in the right directory. I wasn't sure whether I could put several queries in the same .sql file (see CopyTables.sql) so let me know if you need these to be split into individual .sql files.

### CODE REVIEW

**Comment by xhoenner** [comment]
@jkburges it says all checks have failed, any idea what I have done wrong?

**Comment by jkburges** [comment]
I think there's a problem with the way grails is being installed (or not) on Travis. I'll take a look.

**Comment by jkburges** [comment]
Aside from the issue which is hopefully resolved in https://github.com/aodn/aatams/pull/260, this PR is failing with several errors due to missing views/tables.  See:
https://gist.github.com/jkburges/046c207268aefb2d2b75

@xhoenner, I can give you a hand getting set up to run the tests from your workstation so you can fix things more easily.

**Comment by jkburges** [comment]
> wasn't sure whether I could put several queries in the same .sql file

This seems to be ok btw.

**Comment by xhoenner** [comment]
> @xhoenner, I can give you a hand getting set up to run the tests from your workstation so you can fix things more easily.

That'd be great yes! Come and see me when you have a bit of time.

> this PR is failing with several errors due to missing views/tables.

I've addressed these in https://github.com/aodn/aatams/commit/1a56cbd21ab37f98f44934ff2584c7c6649b9d8a

**Pull request merged**
