### PR TITLE
Google Analytics for ExportDownloadDetections

### PR DESCRIPTION
**Pull request by pmbohm**

### CODE REVIEW

**Comment by pmbohm** [comment]
For https://github.com/aodn/backlog/issues/735

**Comment by jonescc** [comment]
Is this complete?  Can't get any info of filters used.

**Comment by pmbohm** [comment]
It would need to be merged @jonescc

**Comment by pmbohm** [comment]
@jonescc I made an account for my dev box in my name if you want to see it work?

**Comment by jonescc** [comment]
Shouldn't I see the events that would be sent in the console?

**Pull request merged**
