### PR TITLE
241 validation

### PR DESCRIPTION
**Pull request by julian1**
Needs review and testing by @xhoenner

### CODE REVIEW

**Comment by anguss00** [comment]
Going to pass an eye over this @julian1

**Comment by anguss00** [comment]
Damn sdkman

**Comment by julian1** [comment]
yeah, travis appears broken.

**Comment by xhoenner** [comment]
Nice work @julian1, the logic seems to behave according to the specifications outlined previously. Note that I've also checked how this PR modifies the number of detections across all tags: it brings down the number of valid detections from 75.2 to 62.6 millions so we'll have to add a message in the corresponding reports @jachope once this PR gets deployed to production.

A few minor things to iron out @julian1 :
  * the error icon doesn't show up when looking at invalid receivers, see [here](http://aatams-test-instance/aatams-after/receiver/show/81653330).
  * no pop-up error message when clicking on the missing error icon when recovery date < deployment date within a record, see [here](http://aatams-test-instance/aatams-after/receiver/show/19975071#).
  * error messages could be more human readable by using table column names.

**Comment by xhoenner** [comment]
@julian1 where are you at with this one?

**Comment by julian1** [comment]
I'm working on a different board task. I can switch after lunch if the aatams stuff needs priority - perhaps it does so that you can test?

**Comment by xhoenner** [comment]
it'd be great if you could do so yes. @fjaine will be in Hobart this week so I won't have much time to review PRs from tomorrow onwards.

**Comment by julian1** [comment]
> the error icon doesn't show up when looking at invalid receivers, see here.

It looks like the virtual path eg. the /aatams bit of the url path has been hardcoded in the view code. see here, https://github.com/aodn/aatams/blob/master/grails-app/views/receiverRecovery/_recoveryList.gsp#L75

When the application is moved from aatams-after to just aatams then the icon shows
eg, http://aatams-test-instance/aatams/receiver/show/81653330?null

**Comment by julian1** [comment]
> no pop-up error message when clicking on the missing error icon when recovery date < deployment date within a record, see here.

I'm going to have to use a debugger for this. It looks like there are multiple error messages and the join doesn't work, and it ends up outputting nothing/ or throwing.

**Comment by julian1** [comment]
> A few minor things to iron out @julian1 :
 
Hi @xhoenner. I think I've addressed all points. see here,

http://aatams-test-instance/aatams/receiver/show/19975071?null

http://aatams-test-instance/aatams/receiver/show/81653330#

**Pull request merged**
