### PR TITLE
Make 'Slope', 'Intercept', and 'Unit' fields compulsory for 'PINGER' …

### PR DESCRIPTION
**Pull request by akashisama**
…and 'RANGE_TEST' transmitter types
Implements acceptance criteria 1 and 2 of https://github.com/aodn/backlog/issues/783

### CODE REVIEW

**Comment by xhoenner** [comment]
A few things to address before this can be merged:
  * Currently users aren't able to leave the sensor slope and intercept fields blank for transmitter_type in (PRESSURE, TEMPERATURE or ACCELEROMETER), which is what we want, but values for those fields can be equal to 0, which isn't currently allowed by the underlying web app logic. Also there's no red asterisk next to the Unit field.
screen shot 2018-02-16 at 4 12 34 pm
  * When selecting an existing tag, click on Edit, the Ping ID code field becomes empty (1st issue). Then click on Add sensor. Fill out the pop-up form (transmitter type and ping ID code) but leaving slope/intercept fields blank and clicking Create, the error returned by the UI is 'Code Map with invalid transmitter type'. Also on that same pop-up the unit field doesn't come with a red asterisk, by default there's no pre-filled unit value, and this same field is editable while it shouldn't be.
  * When creating a tag, the Project field can now be made null despite the red asterisk indicating it's a mandatory field.

**Comment by pmbohm** [comment]
_"When creating a tag, the Project field can now be made null despite the red asterisk indicating it's a mandatory field."_
@xhoenner From what i can tell Project has never been mandatory.  Should it be?

**Comment by xhoenner** [comment]
> Project has never been mandatory. Should it be?

Hmm, thought it's always been mandatory given the red asterisk there! Yes, it should be a mandatory field, otherwise there's no way of telling who a tag belongs to, and it is impossible for the tag owner to edit his/her tag specs.

**Comment by xhoenner** [comment]
After clearing the browser cache I could see the asterisk next to the Unit field so that's alright. Also tested https://github.com/aodn/aatams/pull/420/commits/7e7da36c2183a24635a2e6ec4230ab0365f4fc45 and looking good now Phil with zeros for slope and/or intercept. 

Were you able to re-create the 'Code Map with invalid transmitter type' error?

**Comment by jonescc** [comment]
The tests are buggered as well.   Need to revert to tests just testing issues with the new functionality

**Comment by xhoenner** [comment]
Tested this PR on the dev instance and looking fully functional @akashisama

**Pull request merged**
