### PR TITLE
Change tag status from deployed to new for data entry

### PR DESCRIPTION
**Pull request by xhoenner**
Following up from #291, @astecken requested changing tag status from 'DEPLOYED' to 'NEW' for a list of tags he sent me, see https://github.com/aodn/aatams/issues/291#issuecomment-203206567.

### CODE REVIEW

**Comment by astecken** [comment]
@xhoenner Does the tab 'files changed' and the script within mean that it has been changed? :)

**Comment by xhoenner** [comment]
Yes I've changed it from my end, but I don't think those changes have been applied to the db yet. Have they @julian1?

**Comment by julian1** [comment]
I really wish we had this ad-hoc sql automated so that anyone can easily determine what's been run and what hasn't.

To my knowledge, none of the PR code has been run/deployed, except for the carry over from last iteration.

**Comment by astecken** [comment]
Can you let me know when it has been implemented, please? I need to get these tags in asap. Thanks!

**Comment by julian1** [comment]
@astecken, @xhoenner All good, except for #268. I ran it again after the others (in case there was a dependency) but got the same error result.
```
jfca@3-aws-syd:~/aatams$ sudo -u postgres psql -d aatams3 -f ./scripts/sql/xavier-changes-2016_April/aatamsDB_queries_#268.sql 2>&1 | tee 268.txt
SET
BEGIN
psql:./scripts/sql/xavier-changes-2016_April/aatamsDB_queries_#268.sql:7: ERROR:  update or delete on table "animal_release" violates foreign key constraint "fk8eb3adf9b5c10085" on table "animal_measurement"
DETAIL:  Key (id)=(2854037) is still referenced from table "animal_measurement".
psql:./scripts/sql/xavier-changes-2016_April/aatamsDB_queries_#268.sql:16: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:./scripts/sql/xavier-changes-2016_April/aatamsDB_queries_#268.sql:36: ERROR:  current transaction is aborted, commands ignored until end of transaction block
ROLLBACK
jfca@3-aws-syd:~/aatams$ less 268.txt 
jfca@3-aws-syd:~/aatams$ sudo -u postgres psql -d aatams3 -f ./scripts/sql/xavier-changes-2016_April/aatamsDB_queries_#294.sql 2>&1 | tee 294.txt
SET
BEGIN
UPDATE 232
UPDATE 239
 st_astext | st_astext 
-----------+-----------
(0 rows)

UPDATE 1
UPDATE 1
 st_astext | st_astext 
-----------+-----------
(0 rows)

COMMIT
jfca@3-aws-syd:~/aatams$ less 294.txt 
jfca@3-aws-syd:~/aatams$ less 294.txt 
jfca@3-aws-syd:~/aatams$ sudo -u postgres psql -d aatams3 -f ./scripts/sql/xavier-changes-2016_April/aatamsDB_queries_#291.sql 2>&1 | tee 291.txt
SET
BEGIN
UPDATE 214
COMMIT
jfca@3-aws-syd:~/aatams$ less 291.txt 
jfca@3-aws-syd:~/aatams$ sudo -u postgres psql -d aatams3 -f ./scripts/sql/xavier-changes-2016_April/aatamsDB_queries_#301.sql 2>&1 | tee 301.txt
SET
BEGIN
DELETE 6
COMMIT
```

**Comment by xhoenner** [comment]
Thanks @julian1, it's weird that I didn't get this error when I ran this script on the AATAMS dev instance. How about I get rid of the 'DELETE' bit of the code and push the changes in another PR?

@astecken would you mind asking whoever's in charge of the Gulf of St Vincent monitoring project to add a tagging event for those two tag releases:
https://aatams.emii.org.au/aatams/animalRelease/show/2854053
https://aatams.emii.org.au/aatams/animalRelease/show/2854037

**Comment by julian1** [comment]
> How about I get rid of the 'DELETE' bit of the code and push the changes in another PR?

that's fine by me

**Comment by astecken** [comment]
The two tagging events were updated. Let me know if you need anything else!

**Comment by julian1** [comment]
```
jfca@3-aws-syd:~/aatams$ sudo -u postgres psql -d aatams3 -f   ./scripts/sql/xavier-changes-2016_April/aatamsDB_queries_#268.sql
SET
BEGIN
UPDATE 178
UPDATE 2
COMMIT
```

**Comment by julian1** [comment]
@xhoenner , I'm posting the logs here, so I know whether a script has been run or not. 

```
jfca@3-aws-syd:~/aatams$ sudo -u postgres psql -d aatams3 -f scripts/sql/xavier-changes-2016_April/aatamsDB_queries_#309.sql 2>&1 | tee 309.txt
SET
BEGIN
DELETE 1
COMMIT
jfca@3-aws-syd:~/aatams$ sudo -u postgres psql -d aatams3 -f scripts/sql/xavier-changes-2016_April/aatamsDB_queries_#310.sql 2>&1 | tee 310.txt
SET
BEGIN
UPDATE 19
DELETE 1
COMMIT
jfca@3-aws-syd:~/aatams$ sudo -u postgres psql -d aatams3 -f scripts/sql/xavier-changes-2016_April/aatamsDB_queries_#312.sql 2>&1 | tee 312.txt
SET
BEGIN
DELETE 1
DELETE 1
DELETE 1
DELETE 1
COMMIT
jfca@3-aws-syd:~/aatams$ 
```

**Pull request merged**
