### PR TITLE
fix #385

### LINKED ISSUE #385: 'Custom Validation' ERROR when deploying a receiver
Migrated from https://github.com/aodn/aatams-content/issues/60, originally reported by @fjaine.

@xhoenner I tried to deploy two receivers as part of the AATAMS Glenelg installation:

Receiver 101686: deployed 4/8/16 at GL 7 Station
Receiver 101679: deployed 4/8/16 at GL 8 Station
There is no deployment time available for these deployments (not recorded on the day) so I left it as 00:00 UTC.

When creating the deployment, the following error appeared. Any idea what's preventing me from deploying these receivers?

screen shot 2017-02-09 at 2 34 28 am

### PR DESCRIPTION
**Pull request by julian1**
for @xhoenner

### CODE REVIEW

**Comment by julian1** [comment]
see https://github.com/aodn/aatams/issues/385#issuecomment-281885065

**Comment by julian1** [comment]
Don't merge. I'm deploying to aatams-test-instance for testing

**Comment by julian1** [comment]
deployed to http://aatams-test-instance/aatams/ version 3.23.0

**Comment by xhoenner** [comment]
Looking good @julian1, tested for a few scenarios and all got me the expected behaviour. Nice work, can be deployed on prod.

**Pull request merged**
