### PR TITLE
Changed "Tagging" to "Tracking" in the README.md

### PR DESCRIPTION
**Pull request by xhoenner**
@jachope has requested that change in the readme file. Please merge @jkburges.

This now also includes the changes specified in https://github.com/aodn/backlog/issues/206

### CODE REVIEW

**Comment by jkburges** [comment]
There are [a few other places](https://github.com/aodn/aatams/search?utf8=%E2%9C%93&q=Australian+Animal+Tagging+and+Monitoring+System&type=Code) where this probably should be changed, should we do that as part of this?

**Comment by jkburges** [comment]
Here also: https://github.com/aodn/aatams/blob/master/web-app/images/IMOS-logo.png
I have no idea where that image came from (@pmbohm?) mind you.

**Comment by xhoenner** [comment]
> There are a few other places where this probably should be changed, should we do that as part of this?

I'd say so, unless @jachope thinks otherwise?

**Comment by jkburges** [comment]
Oops that should be https://github.com/aodn/aatams/blob/master/web-app/images/IMOS_Facility_8.png above.

**Comment by pmbohm** [comment]
@jkburges Marian has created a new png on the shared drive. Heres a copy
imos_facility_8_animal tracking

**Comment by jkburges** [comment]
I've updated the image.  Thanks @pmbohm

**Comment by xhoenner** [comment]
I made the additional changes that you suggested @jkburges, happy to merge?

**Comment by jkburges** [comment]
@danfruehauf "jkburges1, the new logo has a white background, is that intended"?

Doesn't seem to matter about the transparency since it's on a white background - it looks ok to me, but maybe transparent is better anyway?

**Comment by jkburges** [comment]
This size of the image has changed but also it's being scaled now, see: https://github.com/aodn/aatams/commit/a6350638f24dc6bf72443641343917c0e386ae11#diff-7f7aa240d88594f7934b9329c1c111beR146

**Comment by danfruehauf** [comment]
> Doesn't seem to matter about the transparency since it's on a white background - it looks ok to me, but maybe transparent is better anyway?

I think it'd be cleaner to have the image transparent. So when the department of something and something wants to change all our backgrounds to black, the logo will still work ;)

**Comment by jkburges** [comment]
I tend to agree.  Malcolm is bound to want a black background.  @pmbohm I can haz a transparent image pls?

**Comment by jkburges** [comment]
GTG now.

**Pull request merged**
