### PR TITLE
Make project a mandatory field when creating/editing tags

### PR DESCRIPTION
**Pull request by xhoenner**
Simple PR that addresses https://github.com/aodn/aatams/issues/350 by making the project property compulsory. Ready for review @julian1

### CODE REVIEW

**Comment by pmbohm** [comment]
@julian Should i fix the test for Xav? or is it unwanted now?

**Comment by julian1** [comment]
Lets wait until @xhoenner can confirm this is still needed.

**Comment by julian1** [comment]
actually it's very low risk. probably fine to merge.

**Comment by xhoenner** [comment]
Yes this PR's been sitting here for ages, didn't know if my code changes were valid or not since Travis' checks failed. Still wanted so feel free to merge if you think the syntax is correct.

**Comment by julian1** [comment]
build stability are separate issues,

jenkins https://github.com/aodn/aatams/issues/383

travis https://github.com/aodn/aatams/issues/359

**Pull request merged**
