### PR TITLE
Hiding delete functionality, since it's a bit "dangerous" the way things...

### PR DESCRIPTION
**Pull request by jkburges**
... currently are.  Refer to https://github.com/aodn/aatams/issues/202 for an example of what can go wrong.

### CODE REVIEW

**Comment by dnahodil** [comment]
I don't think this will be sufficient as it is. The CSS change probably won't be seen as the user will have visited the site already and have a cached version of the file. We could fix this by versioning the CSS as we do in the Portal.

Also, I think this change will affect all delete buttons in the app. Was it your intent to prevent deletion of all types of entities, @jkburges?

**Comment by jkburges** [comment]
> "...versioning the CSS as we do in the Portal."
Ok.

> "Also, I think this change will affect all delete buttons in the app. Was it your intent to prevent deletion of all types of entities, @jkburges?"
Yes.

**Comment by jkburges** [comment]
@dnahodil is CSS in the portal in fact versioned? It doesn't *seem* to be, but maybe I'm missing something...

**Comment by dnahodil** [comment]
It only happened recently. See https://github.com/aodn/aodn-portal/blob/master/grails-app/views/_public_theme_includes.gsp#L15

**Comment by jkburges** [comment]
@dnahodil 408be55

**Comment by dnahodil** [comment]
Looks good, @jkburges.

**Pull request merged**
