### PR TITLE
Proposed solution for Issue #208

### PR DESCRIPTION
**Pull request by dnahodil**
**Not for merging, yet**

This is the idea I have been following to address #208. I think this solution should work and it just needs to be followed-through a bit further. The unit tests are currently failing (but not as expected) so I need to look into that.

Other considerations:
* There might be a better name than `surgery_with_end_date` for the new view.
* It seems odd to calculate what is essentially an 'end date' for surgeries. However they are more relevant than releases to determine which detection is valid form what I understand.
* We probably need to use the new view to derive the `detections_per_station_count` so that it is more accurate. I haven't looked into that yet.
* I haven't tested the CSV export through the webapp, yet.

I will continue with this later in the iteration if time permits.

### CODE REVIEW

**Comment by jkburges** [comment]
I think it's correct to have the end date against `surgery` (as opposed to `release`), as each tag attached to an animal during a surgery may have a different life time, may be recovered at different times etc.

**Comment by jkburges** [comment]
This change will also have to be performance tested.

**Comment by dnahodil** [comment]
Some of the broken tests are because of the way detections are matched with surgeries. The proposed change has taken out detections which happen before surgeries for that tag, it might also take out detections without surgeries -- will need to check. Both of those are incorrect and those detections should still exists, just not be linked to surgeries.

**Comment by dnahodil** [comment]
See #276 with improved solution

**Pull request closed without merging**
