### PR TITLE
Remove VRL and RLD file types for detection uploads

### PR DESCRIPTION
**Pull request by xhoenner**
as those file types are not supported by the web app anyway, and result in users wrongly believing that those files are being processed. For further information see https://github.com/aodn/aatams/issues/210#issuecomment-313271784.

When I implemented this change on the dev-instance VM it seemed okay @bhasin85, however I wasn't able to test the upload functionality, and neither was I able to on the test-instance. Maybe @julian1 never deployed that functionality for these two VMs?

### CODE REVIEW

**Comment by julian1** [comment]
> Maybe @julian1 never deployed that functionality for these two VMs?

Hi @xhoenner, not sure I ever looked at, or tested uploads. The data dirs should exist, but perhaps something is needed in the tomcat config?

**Comment by bhasin85** [comment]
@xhoenner Trigger the build again.... It should pass all the checks.

**Comment by xhoenner** [comment]
Re-triggered the build for both PRs, failed for both, looking at Travis' logs there are still lots of errors in there @bhasin85

**Comment by jonescc** [comment]
Looks like we have some test data that uses those types.  We should remove them from the test data setup as well.

**Comment by bhasin85** [comment]
@xhoenner  I would like to test out this functionality and will therefore need your help with the setup.

**Comment by bhasin85** [comment]
Can you please update the branch again with Master.... Thanks :+1:

**Comment by xhoenner** [comment]
> Can you please update the branch again with Master....

See https://github.com/aodn/aatams/pull/395/commits/15f282cfa03527386506e239293c08bf5f5c885e @bhasin85. Got the following error though during the Travis build

```bash
ERROR:  could not access file "$libdir/postgis-2.3": No such file or directory
```

**Pull request merged**
