### PR TITLE
Migration to recalculate all ProjectRole permissions

### PR DESCRIPTION
**Pull request by dnahodil**

### CODE REVIEW

**Comment by dnahodil** [comment]
Hold tight on this. The tests are failing (unrelated) but I also don't think this is working as I thought it was.

**Comment by dnahodil** [comment]
Test fixed with a rebase from master. This is good to be reviewed now. I think it works as we want.

**Comment by jkburges** [comment]
I would like to see this run against a copy of production, and a diff of the before and after produced.  I don't mind if it happens in systest (since there's a recent enough copy there) but in that case, we'd need to be careful this change does make it in to prod before this check happens...  

@dnahodil what you wanna do?

**Comment by dnahodil** [comment]
Yeah, good point.

What about if I put a blocker on the AATAMS release task to stop it being released to prod prematurely. I can also add a ticket alongside 'Smoke test' for us to specifically check this behaviour. Thoughts?

**Comment by jkburges** [comment]
Put a blocker and a note about what the blocker is, that's fine.

**Comment by dnahodil** [comment]
Done and done.

**Pull request merged**
