### PR TITLE
Added section describing the application features

### PR DESCRIPTION
**Pull request by jkburges**
This is to help guide future work on AATAMS.

### CODE REVIEW

**Comment by jkburges** [comment]
Comments please @dnahodil @xhoenner @ktattersall @pblain.  I *could* go in to much more detail, but I think it's more useful to keep it fairly high level.  Perhaps also there are some major features which I have missed (I haven't looked at code in order to write this bit of doco).

**Comment by dnahodil** [comment]
Looks okay to me, @jkburges.

Just two small thoughts, neither too serious.
* Maybe the 'detection and event data' point could be expanded to 'animal detection and receiver event data'. I thought that might be a bit more clear. Would everyone know what receiver events are? or are there some people who only deal with tags and therefore wouldn't be familiar?
* In the security section is it worth mentioning the two big access restrictions (embargoed data and protected species). Not a blurb, just a sentence or something parenthetical.

**Comment by jkburges** [comment]
@dnahodil 6304b8e5986e0395

**Comment by dnahodil** [comment]
:+1:

**Pull request merged**
