### PR TITLE
Fix overlapping deploys

### PR DESCRIPTION
**Pull request by jkburges**
This PR consists of the following:

1. validate that deployment date is >= initialisation date
2. auto-correct overlapping deployments (by setting initialisation date equal to deployment date)
3. auto-correct initialisation date > deployment date (as above)
4. a URL to list receivers having invalid deployments (https://aatams.emii.org.au/aatams/receiver/listInvalid)
5. highlighting of invalid deployments on the receiver details page (e.g. https://aatams.emii.org.au/aatams/receiver/show/2917374)

2) and 3) above can potentially be making some incorrect assumptions, as such, any affect rows are logged, and we can provide a report of these after this version is deployed.  We also have the capacity to rollback the changes in case a mistake is found.

### CODE REVIEW

**Comment by jkburges** [comment]
40aa729 is only showing up because of some merge/rebase magic (I think).

**Comment by jkburges** [comment]
To rollback (in case anyone wants to test it):

```
$ grails dbm-rollback-count 1 --defaultSchema=aatams
```

**Comment by jkburges** [comment]
@xhoenner @astecken when this is released, there will still be some receivers (95) with deployments that need to be corrected manually.

Unfortunate that the lack of validation leading to this problem has gone undetected for so long, but this release should at least stop *new* invalid deployments/recoveries from entering the system.

**Comment by dnahodil** [comment]
Imma check this out

**Comment by dnahodil** [comment]
Was `src/groovy/au/org/emii/aatams/data/.DevelopmentDataInitialiser.groovy.swp` added deliberately, or is it a mistake?

**Comment by jkburges** [comment]
> Was src/groovy/au/org/emii/aatams/data/.DevelopmentDataInitialiser.groovy.swp added deliberately, or is it a mistake?

image

**Comment by dnahodil** [comment]
Checked and seems to be working fine. I tried the rollback and that worked well.

**Comment by jkburges** [comment]
This is GTG (again). I've [tagged the auto-correct attempt](https://github.com/aodn/aatams/releases/tag/overlapping_deployment_auto_correct) in case we want to bring it back.

**Pull request merged**
