### PR TITLE
Fix #268

### LINKED ISSUE #268: Capture and release location should be mandatory fields
In https://aatams.emii.org.au/aatams/animalRelease/create, `Capture Location` and `Release Location` should both be mandatory fields to avoid having releases with no lat/lon coordinates.

### PR DESCRIPTION
**Pull request by xhoenner**
Addresses https://github.com/aodn/aatams/issues/268#issue-111758919 and https://github.com/aodn/aatams/issues/268#issuecomment-191045251 to prevent people from not entering capture and release locations and get rid of the obsolete animal field in the tag release page

### CODE REVIEW

**Comment by julian1** [comment]
@xhoenner Is there a need to change the show view as well? https://github.com/aodn/aatams/blob/fix268/grails-app/views/animalRelease/show.gsp

**Comment by xhoenner** [comment]
> @xhoenner Is there a need to change the show view as well?

No, only the edit and create views needed to be changed.

**Comment by julian1** [comment]
Is there a need to also enforce as non-null in the db also?

**Comment by xhoenner** [comment]
Yes that's the plan, but for that to happen I first need Andre to fix up the releases with no release or capture locations (#268).

**Pull request merged**
