### PR TITLE
Re-enable deletes aodn/backlog/issues/229

### PR DESCRIPTION
**Pull request by pmbohm**

### CODE REVIEW

**Comment by pmbohm** [comment]
Shouting now at sysadmins now if they attempt to delete

screen shot 2016-01-21 at 11 41 37 am

**Comment by julian1** [comment]
I can't find #285. When I click https://github.com/aodn/aatams/issues/285 github redirects me to this pull-request.

@xhoenner wasn't there something to do with enabling soft-deletes? Eg. so that a column in the database row gets marked as deleted, rather than actually deleting the row. Was that encompassed/related to this work?

**Comment by xhoenner** [comment]
@julian1 this PR refers to this issue https://github.com/aodn/aatams/issues/204. See @jkburges' comments regarding soft deletes

**Comment by pmbohm** [comment]
@julian For better or worse this pull request follows the requirements of aodn/backlog#229 only

**Comment by xhoenner** [comment]
The delete functionality has been disabled precisely because it was threatening the integrity of the data in the database. What @jkburges suggested in https://github.com/aodn/aatams/issues/204 was to introduce a soft delete feature to avoid the inadvertent loss of data. Simply re-enabling the delete functionality will cause more problems than anything else, see https://github.com/aodn/aatams/issues/202 which forced us to restore a backup of the db. 

I'd say that the requirements laid out in https://github.com/aodn/backlog/issues/229 are not representative of https://github.com/aodn/aatams/issues/204 and therefore need to be refined @pblain.

**Comment by pblain** [comment]
@xhoenner ,  Andre asked for the delete feature to be re-enabled: https://github.com/aodn/aatams/issues/204#issuecomment-97605001

We are doing our best to fix bugs in the existing feature set - but we are not adding new features.  Up to you whether you want the delete feature restored to function as it was designed (i.e. hard delete), or to leave it disabled.

**Comment by astecken** [comment]
The reality is that I need to get the delete function back asap to clean up the database, e.g. double entries, wrong entries, etc. There shouldn't be a delete button for everyone but for me as a sysadmin. Thanks for sorting this out!

**Comment by xhoenner** [comment]
I'm aware that @astecken wants the delete functionality re-enabled but @jkburges disabled it originally to prevent the loss of data: https://github.com/aodn/aatams/issues/204#issue-58008550.

I thought it was clear in your mind that fixing #204 meant proceeding as @jkburges suggested and implement the soft-delete functionality since just re-enabling the delete functionality threatens the integrity of the database. I am surprised that we're having this disagreement at this stage of the iteration, I would have thought that the details of getting #204 fixed would have come up during conversations with Rog, @jachope and @smancini, and then again during the developers' planning meeting. 

I don't think it is wise to proceed without the soft-delete feature, it's just a recipe for wasting developers' time with VITs to restore the AATAMS db. As explained to @smancini, providing @astecken with a way to delete content through the web app (which in this case requires a new feature or a remodel of the existing delete functionality depending on how you want to look at things) is the only approach we have to knock down two (https://github.com/aodn/aatams/issues/240 and https://github.com/aodn/aatams/issues/241) of the remaining five high priority bugs. 

@pmbohm, @julian1 do you agree with the above?

**Comment by julian1** [comment]
For my part, I believe this is a matter for JPSR.

**Comment by julian1** [comment]
Closing for now, following https://github.com/aodn/backlog/issues/229

**Pull request closed without merging**
