### PR TITLE
Call receiver export delete operation async in order to prevent apache 443 errors

### PR DESCRIPTION
**Pull request by anguss00**
Fixes issue #106

### CODE REVIEW

**Comment by dnahodil** [comment]
Hey @anguss00. This all looks really good. Just a few comments, nothing too serious.

Let me know if you have any questions.

**Comment by anguss00** [comment]
Cheers @dnahodil, I'll just make those modfications

**Comment by anguss00** [comment]
Changes made @dnahodil

**Comment by dnahodil** [comment]
Nice work.

**Pull request merged**
