### PR TITLE
fix #372

### LINKED ISSUE #372: Can't edit receiver deployment anymore
Go to the [receiver deployment page](https://animaltracking.aodn.org.au/receiverDeployment/list) or try editing a [particular receiver deployment](https://animaltracking.aodn.org.au/receiver/show/58827175). Click on the i icon to the left and you'll get the error below, which probably arose from fixing #241 through https://github.com/aodn/aatams/pull/358 @julian1. 

screen shot 2017-01-10 at 7 40 02 am

@pblain this should be a VIT: if we're not fixing up this bug then nobody will be able to edit their receiver deployment metadata.

### PR DESCRIPTION
**Pull request by julian1**
Don't merge.

### CODE REVIEW

**Comment by julian1** [comment]
Deployment number exists in the database, 

```
                   Table "aatams.receiver_deployment"
              Column              |           Type           | Modifiers 
----------------------------------+--------------------------+-----------
...
 deploymentdatetime_timestamp     | timestamp with time zone | not null
 deploymentdatetime_zone          | character varying(255)   | not null
 deployment_number                | integer                  | 
...
```
so I don't know why it appears as a transient field in the domain class? Perhaps @jkburges knows? Changing it to an ordinary grails property fixes the issue.

Needs @xhoenner to test

**Comment by julian1** [comment]
Thinking about it some more, and I suspect deployment number will need to be computed dynamically due to the new matching sql and the static values in the database won't be right.

ie. it should increment for each row in the view,

http://144.6.227.62/aatams/receiver/show/19975071?null

**Comment by jkburges** [comment]
From memory, `deployment number` used to be a field that was entered by users - but we figured that it is something that should in fact be derived (from the deployments in the DB) so that is why it would be a transient field.  Not sure why that column wasn't cleaned up from the DB though.

**Comment by julian1** [comment]
Thanks @jkburges. Yes, I think I rushed this, without considering that the matching going on.

**Pull request closed without merging**
