### PR TITLE
Add queries to address #241

### PR DESCRIPTION
**Pull request by xhoenner**
Addresses #241.

First part of script deals with `receiver deployment dates` > `receiver initialisation dates` by correcting erroneous initialisation dates to be equal to deployment dates - 5 minutes.

Only five entries had `receiver recovery dates` < `receiver deployment dates`, these are listed just below, probably best if left for @astecken as I wasn't sure which of the two above dates had to be changed.

receiver_deployment_id | installation_name | station_name | receiver_name | invalid_reason | initialisation_datetime | deploymentdatetime_datetime | recoverydatetime_datetime
---------------------- | ----------------- | ------------ | ------------- | -------------- | ----------------------- | --------------------------- | -------------------------
19975968 | Ningaloo Reef | MB6A | VR2W-101834 | DEPLOY/RECOV OUT OF ORDER | 2009-05-25T04:47:10+09:30 | 2009-11-06T02:53:51+10:30 | 2009-05-25T04:15:59+09:30
19975804 | Ningaloo Reef | MB21A | VR2W-101841 | DEPLOY/RECOV OUT OF ORDER | 2007-11-26T02:11:01+10:30 | 2009-11-25T23:30:00+10:30 | 2008-10-12T05:28:49+10:30
19975996 | Ningaloo Reef | MB26 | VR2W-101862 | DEPLOY/RECOV OUT OF ORDER | 2009-05-22T01:21:57+09:30 | 2009-11-26T06:28:52+10:30 | 2009-05-22T00:51:57+09:30
23143788 | Wenlock River | Overhang | VR2W-103548 | DEPLOY/RECOV OUT OF ORDER | 2008-08-19T23:45:29+00:00 | 2008-12-10T23:59:29+00:00 | 2008-12-10T02:46:47+00:00
3114925 | AATAMS Port Stephens | PS5 | VR2W-109645 | DEPLOY/RECOV OUT OF ORDER | 2011-03-09T20:07:00+00:00 | 2011-10-24T13:20:00+11:00 | 2011-10-24T10:15:19+11:00

The second part of the script was generated in R and deals with receiver deployment/recovery overlaps that occurred within 24 hours of one another.  For all other receiver overlaps, I suggest @astecken contacts receiver owners to fix these entries manually, see below.

email_address | receiver_name
------------- | -------------
  | VR2W-101998
 adam.barnett@utas.edu.au | VR2-1849
 amy.smoothey@industry.nsw.gov.au | VR2W-100473
 amy.smoothey@industry.nsw.gov.au | VR2W-100475
 amy.smoothey@industry.nsw.gov.au | VR2W-100723
 amy.smoothey@industry.nsw.gov.au | VR2W-100726
 amy.smoothey@industry.nsw.gov.au | VR2W-102353
 amy.smoothey@industry.nsw.gov.au | VR2W-103743
 amy.smoothey@industry.nsw.gov.au | VR2W-103760
 amy.smoothey@industry.nsw.gov.au | VR2W-106277
 amy.smoothey@industry.nsw.gov.au | VR2W-106956
 amy.smoothey@industry.nsw.gov.au | VR2W-107083
 amy.smoothey@industry.nsw.gov.au | VR2W-109578
 amy.smoothey@industry.nsw.gov.au | VR2W-109593
 amy.smoothey@industry.nsw.gov.au | VR2W-109603
 amy.smoothey@industry.nsw.gov.au | VR2W-109620
 amy.smoothey@industry.nsw.gov.au | VR2W-110485
 amy.smoothey@industry.nsw.gov.au | VR2W-110498
 amy.smoothey@industry.nsw.gov.au | VR2W-110501
 amy.smoothey@industry.nsw.gov.au | VR2W-110510
 amy.smoothey@industry.nsw.gov.au | VR2W-111365
 amy.smoothey@industry.nsw.gov.au | VR2W-112175
 amy.smoothey@industry.nsw.gov.au | VR2W-112179
 amy.smoothey@industry.nsw.gov.au | VR2W-112841
 amy.smoothey@industry.nsw.gov.au | VR2W-112847
 amy.smoothey@industry.nsw.gov.au | VR2W-112853
 amy.smoothey@industry.nsw.gov.au | VR2W-115226
 amy.smoothey@industry.nsw.gov.au | VR2W-115228
 amy.smoothey@industry.nsw.gov.au | VR2W-115229
 amy.smoothey@industry.nsw.gov.au | VR2W-115232
 andre.steckenreuter@sims.org.au | VR2W-107512
 andre.steckenreuter@sims.org.au | VR2W-108126
 andre.steckenreuter@sims.org.au | VR2W-114549
 andre.steckenreuter@sims.org.au | VR2W-114658
 andre.steckenreuter@sims.org.au | VR2W-114670
 andre.steckenreuter@sims.org.au | VR2W-120762
 andre.steckenreuter@sims.org.au | VR4-UWM-250383
 andre.steckenreuter@sims.org.au | VR4-UWM-250387
 andrew.boomer@sims.org.au | VR2W-101713
 andrew.boomer@sims.org.au | VR2W-101758
 andrew.boomer@sims.org.au | VR2W-101774
 andrew.boomer@sims.org.au | VR2W-105721
 andrew.boomer@sims.org.au | VR2W-105863
 andrew.boomer@sims.org.au | VR2W-106658
 andrew.boomer@sims.org.au | VR2W-106659
 andrew.boomer@sims.org.au | VR2W-106660
 andrew.boomer@sims.org.au | VR2W-106873
 andrew.boomer@sims.org.au | VR2W-114549
 andrew.boomer@sims.org.au | VR2W-114560
 andrew.boomer@sims.org.au | VR4-UWM-250379
 andrew.boomer@sims.org.au | VR4-UWM-250394
 andrew.mcdougall@dnrm.qld.gov.au | VR2W-113914
 andrew.tobin@jcu.edu.au | VR2W-113950
 andrew.tobin@jcu.edu.au | VR2W-113953
 andrew.tobin@jcu.edu.au | VR2W-113958
 andrew.tobin@jcu.edu.au | VR2W-113966
 audrey.schlaff@my.jcu.edu.au | VR2W-101693
 audrey.schlaff@my.jcu.edu.au | VR2W-101849
 audrey.schlaff@my.jcu.edu.au | VR2W-105213
 audrey.schlaff@my.jcu.edu.au | VR2W-105214
 audrey.schlaff@my.jcu.edu.au | VR2W-105215
 audrey.schlaff@my.jcu.edu.au | VR2W-105216
 audrey.schlaff@my.jcu.edu.au | VR2W-105218
 audrey.schlaff@my.jcu.edu.au | VR2W-105220
 audrey.schlaff@my.jcu.edu.au | VR2W-107809
 audrey.schlaff@my.jcu.edu.au | VR2W-112612
 audrey.schlaff@my.jcu.edu.au | VR2W-112614
 audrey.schlaff@my.jcu.edu.au | VR2W-112616
 audrey.schlaff@my.jcu.edu.au | VR2W-112619
 audrey.schlaff@my.jcu.edu.au | VR2W-112620
 audrey.schlaff@my.jcu.edu.au | VR2W-112621
 charlie.huveneers@flinders.edu.au | VR2W-101678
 christopher.gallen@dpi.nsw.gov.au | VR2W-101712
 christopher.gallen@dpi.nsw.gov.au | VR2W-106858
 colin.simpfendorfer@jcu.edu.au | VR2W-125184
 douglas.harding@dnrm.qld.gov.au | VR2W-113882
 douglas.harding@dnrm.qld.gov.au | VR2W-113883
 douglas.harding@dnrm.qld.gov.au | VR2W-113887
 douglas.harding@dnrm.qld.gov.au | VR2W-113891
 douglas.harding@dnrm.qld.gov.au | VR2W-113894
 douglas.harding@dnrm.qld.gov.au | VR2W-113895
 douglas.harding@dnrm.qld.gov.au | VR2W-113915
 douglas.harding@dnrm.qld.gov.au | VR2W-113916
 douglas.harding@dnrm.qld.gov.au | VR2W-113919
 douglas.harding@dnrm.qld.gov.au | VR2W-113921
 douglas.harding@dnrm.qld.gov.au | VR2W-113922
 douglas.harding@dnrm.qld.gov.au | VR2W-113924
 douglas.harding@dnrm.qld.gov.au | VR2W-113925
 douglas.harding@dnrm.qld.gov.au | VR2W-114998
 douglas.harding@dnrm.qld.gov.au | VR2W-115000
 douglas.harding@dnrm.qld.gov.au | VR2W-115002
 douglas.harding@dnrm.qld.gov.au | VR2W-115003
 douglas.harding@dnrm.qld.gov.au | VR2W-120326
 douglas.harding@dnrm.qld.gov.au | VR2W-120330
 douglas.harding@dnrm.qld.gov.au | VR2W-122927
 douglas.harding@dnrm.qld.gov.au | VR2W-122928
 douglas.harding@dnrm.qld.gov.au | VR2W-122929
 douglas.harding@dnrm.qld.gov.au | VR2W-122930
 fergua06@student.uwa.edu.au | VR2W-110020
 fernanda.defaria@my.jcu.edu.au | VR2W-106875
 fernanda.defaria@my.jcu.edu.au | VR2W-111014
 fernanda.defaria@my.jcu.edu.au | VR2W-112757
 fernanda.defaria@my.jcu.edu.au | VR2W-113955
 fernanda.defaria@my.jcu.edu.au | VR2W-114061
 hamish.campbell@uq.edu.au | VR2W-105792
 hamish.campbell@uq.edu.au | VR2W-110433
 james.vandenbroek@sims.org.au | VR2W-104491
 james.vandenbroek@sims.org.au | VR2W-104505
 james.vandenbroek@sims.org.au | VR2W-104524
 james.vandenbroek@sims.org.au | VR2W-122098
 k.mcgregor@murdoch.edu.au | VR2W-101772
 k.mcgregor@murdoch.edu.au | VR2W-101773
 k.mcgregor@murdoch.edu.au | VR2W-101774
 k.mcgregor@murdoch.edu.au | VR2W-101775
 k.mcgregor@murdoch.edu.au | VR2W-101777
 k.mcgregor@murdoch.edu.au | VR2W-101843
 k.mcgregor@murdoch.edu.au | VR2W-101844
 k.mcgregor@murdoch.edu.au | VR2W-101845
 k.mcgregor@murdoch.edu.au | VR2W-101846
 k.mcgregor@murdoch.edu.au | VR2W-101852
 k.mcgregor@murdoch.edu.au | VR2W-101853
 k.mcgregor@murdoch.edu.au | VR2W-101854
 k.mcgregor@murdoch.edu.au | VR2W-101855
 k.mcgregor@murdoch.edu.au | VR2W-101856
 k.mcgregor@murdoch.edu.au | VR2W-101858
 k.mcgregor@murdoch.edu.au | VR2W-101878
 kathryn.lee@mq.edu.au | VR2W-101701
 kathryn.lee@mq.edu.au | VR2W-101759
 kathryn.lee@mq.edu.au | VR2W-101762
 kathryn.lee@mq.edu.au | VR2W-101794
 kathryn.lee@mq.edu.au | VR2W-105854
 kathryn.lee@mq.edu.au | VR2W-105858
 kathryn.lee@mq.edu.au | VR2W-105863
 kathryn.lee@mq.edu.au | VR2W-106231
 kathryn.lee@mq.edu.au | VR2W-111276
 kathy.townsend@uq.edu.au | VR2W-101740
 kathy.townsend@uq.edu.au | VR2W-109058
 kathy.townsend@uq.edu.au | VR2W-109059
 krystlekeller7@gmail.com | VR4-UWM-250392
 l.couturier@uq.edu.au | VR2W-109056
 l.couturier@uq.edu.au | VR2W-109057
 leanne.currey@my.jcu.edu.au | VR2W-112757
 mario.espinoza@my.jcu.edu.au | VR2W-113967
 matt.taylor@dpi.nsw.gov.au | VR2W-104121
 matt.taylor@dpi.nsw.gov.au | VR2W-110483
 matt.taylor@dpi.nsw.gov.au | VR2W-110508
 matt.taylor@dpi.nsw.gov.au | VR2W-111363
 michael.drew@flinders.edu.au | VR2W-101336
 michael.drew@flinders.edu.au | VR2W-101678
 michael.drew@flinders.edu.au | VR2W-101685
 michael.drew@flinders.edu.au | VR2W-101798
 michael.drew@flinders.edu.au | VR2W-101915
 michael.drew@flinders.edu.au | VR2W-103305
 michael.drew@flinders.edu.au | VR2W-103353
 nathan.knott@dpi.nsw.gov.au | VR2W-102023
 richard.pillans@csiro.au | VR2W-101822
 richard.pillans@csiro.au | VR2W-101870
 richard.pillans@csiro.au | VR2W-103620
 richard.pillans@csiro.au | VR2W-103621
 richard.pillans@csiro.au | VR2W-103627
 richard.pillans@csiro.au | VR2W-103629
 richard.pillans@csiro.au | VR2W-109841
 richard.pillans@csiro.au | VR2W-109842
 richard.pillans@csiro.au | VR2W-109843
 richard.pillans@csiro.au | VR2W-109844
 richard.pillans@csiro.au | VR2W-109845
 richard.pillans@csiro.au | VR2W-109846
 richard.pillans@csiro.au | VR2W-109848
 richard.pillans@csiro.au | VR2W-109849
 richard.pillans@csiro.au | VR2W-109850
 richard.pillans@csiro.au | VR2W-109851
 richard.pillans@csiro.au | VR2W-109852
 richard.pillans@csiro.au | VR2W-109856
 richard.pillans@csiro.au | VR2W-109864
 richard.pillans@csiro.au | VR2W-109867
 rory.mcauley@fish.wa.gov.au | VR2W-104479
 rory.mcauley@fish.wa.gov.au | VR2W-104498
 rory.mcauley@fish.wa.gov.au | VR2W-104506
 ross.dwyer@uq.edu.au | VR2W-103548
 russ.babcock@csiro.au | VR2W-101866
 russ.babcock@csiro.au | VR2W-105725
 russ.babcock@csiro.au | VR2W-105729
 russ.babcock@csiro.au | VR2W-105732
 russ.babcock@csiro.au | VR2W-111272
 Russ.Bradford@csiro.au | VR2W-103311
 Russ.Bradford@csiro.au | VR2W-103382
 Russ.Bradford@csiro.au | VR2W-103389
 Russ.Bradford@csiro.au | VR2W-103391
 Russ.Bradford@csiro.au | VR2W-103393
 Russ.Bradford@csiro.au | VR2W-103394
 Russ.Bradford@csiro.au | VR2W-109637
 sharon.marshall@dnrm.qld.gov.au | VR2W-113884
 sharon.marshall@dnrm.qld.gov.au | VR2W-113885
 sharon.marshall@dnrm.qld.gov.au | VR2W-113888
 sharon.marshall@dnrm.qld.gov.au | VR2W-113890
 sharon.marshall@dnrm.qld.gov.au | VR2W-113892
 sharon.marshall@dnrm.qld.gov.au | VR2W-113893
 sharon.marshall@dnrm.qld.gov.au | VR2W-113914
 sharon.marshall@dnrm.qld.gov.au | VR2W-113917
 sharon.marshall@dnrm.qld.gov.au | VR2W-113920
 sharon.marshall@dnrm.qld.gov.au | VR2W-113923
 sharon.marshall@dnrm.qld.gov.au | VR2W-114999
 sharon.marshall@dnrm.qld.gov.au | VR2W-120327
 sharon.marshall@dnrm.qld.gov.au | VR2W-120328
 sharon.marshall@dnrm.qld.gov.au | VR2W-120331
 sharon.marshall@dnrm.qld.gov.au | VR2W-120332
 sharon.marshall@dnrm.qld.gov.au | VR2W-120333
 sharon.marshall@dnrm.qld.gov.au | VR2W-122926
 sharon.marshall@dnrm.qld.gov.au | VR2W-125431
 sharon.marshall@dnrm.qld.gov.au | VR2W-125432
 sharon.marshall@dnrm.qld.gov.au | VR2W-125433
 sharon.marshall@dnrm.qld.gov.au | VR2W-125434
 sharon.marshall@dnrm.qld.gov.au | VR2W-125435
 sharon.marshall@dnrm.qld.gov.au | VR2W-125436
 stephbrodie1@gmail.com | VR2W-114410
 stephbrodie1@gmail.com | VR2W-114413
 stephbrodie1@gmail.com | VR2W-115182
 stephbrodie1@gmail.com | VR2W-115185
 stephbrodie1@gmail.com | VR2W-115187
 stephbrodie1@gmail.com | VR2W-121036
 stephbrodie1@gmail.com | VR2W-121304
 thomas.espinoza@dnrm.qld.gov.au | VR2W-113884
 thomas.espinoza@dnrm.qld.gov.au | VR2W-113885
 thomas.espinoza@dnrm.qld.gov.au | VR2W-113888
 thomas.espinoza@dnrm.qld.gov.au | VR2W-113890
 thomas.espinoza@dnrm.qld.gov.au | VR2W-113893
 thomas.espinoza@dnrm.qld.gov.au | VR2W-113914
 thomas.espinoza@dnrm.qld.gov.au | VR2W-113917
 thomas.espinoza@dnrm.qld.gov.au | VR2W-113920
 thomas.espinoza@dnrm.qld.gov.au | VR2W-114999
 thomas.espinoza@dnrm.qld.gov.au | VR2W-120327
 thomas.espinoza@dnrm.qld.gov.au | VR2W-120328
 thomas.espinoza@dnrm.qld.gov.au | VR2W-120331
 thomas.espinoza@dnrm.qld.gov.au | VR2W-120333

### CODE REVIEW

**Comment by astecken** [comment]
I notified all collaborators and will keep you updated re their response. Thanks!

**Comment by astecken** [comment]
Most researchers have serious issues amending any entries as they might overlap with deployments from other projects that used the same receiver at an earlier or later date. It is far too complicated for people to do it themselves and we might need to find a different solution to this problem. I might have to sit down and have discussions with each of the parties to sort this out - unless you guys have a better idea? It would be a very time consuming task...

**Comment by xhoenner** [comment]
> I might have to sit down and have discussions with each of the parties to sort this out - unless you guys have a better idea?

Not sure there's another way around it @astecken since these 234 erroneous receiver deployment/recovery entries will differ from one another. When split between researchers, there aren't really that many records for every single one of them to clean up, see below.

email_address | #_entries_to_fix_up
------------- | -------------------
 amy.smoothey@industry.nsw.gov.au | 28
 douglas.harding@dnrm.qld.gov.au | 23
 sharon.marshall@dnrm.qld.gov.au | 23
 richard.pillans@csiro.au | 20
 k.mcgregor@murdoch.edu.au | 16
 audrey.schlaff@my.jcu.edu.au | 15
 andrew.boomer@sims.org.au | 13
 thomas.espinoza@dnrm.qld.gov.au | 13
 kathryn.lee@mq.edu.au | 9
 andre.steckenreuter@sims.org.au | 8
 michael.drew@flinders.edu.au | 7
 Russ.Bradford@csiro.au | 7
 stephbrodie1@gmail.com | 7
 fernanda.defaria@my.jcu.edu.au | 5
 russ.babcock@csiro.au | 5
 andrew.tobin@jcu.edu.au | 4
 james.vandenbroek@sims.org.au | 4
 matt.taylor@dpi.nsw.gov.au | 4
 kathy.townsend@uq.edu.au | 3
 rory.mcauley@fish.wa.gov.au | 3
 christopher.gallen@dpi.nsw.gov.au | 2
 hamish.campbell@uq.edu.au | 2
 l.couturier@uq.edu.au | 2
 adam.barnett@utas.edu.au | 1
 andrew.mcdougall@dnrm.qld.gov.au | 1
 charlie.huveneers@flinders.edu.au | 1
 colin.simpfendorfer@jcu.edu.au | 1
 fergua06@student.uwa.edu.au | 1
 krystlekeller7@gmail.com | 1
 leanne.currey@my.jcu.edu.au | 1
 mario.espinoza@my.jcu.edu.au | 1
 nathan.knott@dpi.nsw.gov.au | 1
 ross.dwyer@uq.edu.au | 1

**Comment by astecken** [comment]
Will pick this up again when I am back in June then ;)

**Comment by xhoenner** [comment]
@smancini this PR can be reviewed as part of the next iteration

**Comment by julian1** [comment]
Needs to be migrated to https://github.com/aodn/aatams-content

**Comment by xhoenner** [comment]
Migrated to https://github.com/aodn/aatams-content, shall we close this PR then @julian1

**Pull request closed without merging**
